/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni/jni.h>
#include <jni/jni_md.h>
/* Header for class test_ArrayOp */

#ifndef _Included_test_ArrayOp
#define _Included_test_ArrayOp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_ArrayOp
 * Method:    arrayCopy
 * Signature: (Ljava/lang/Object;ILjava/lang/Object;II)V
 */
JNIEXPORT jobject JNICALL Java_test_ArrayOp_arrayCopy
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint);

/*
 * Class:     test_ArrayOp
 * Method:    stringCopy
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_test_ArrayOp_stringCopy
  (JNIEnv *, jclass, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
